version: 0.0
os: linux
files:
  - source: parts
    destination: /home/ubuntu/django/parts/parts
    runas: www-data
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: /home/ubuntu/django/parts/perm_change.sh
      timeout: 300
      runas: root