# Generated by Django 4.0.3 on 2022-03-05 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bottom_cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Charging_Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CPU_Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GRAPHICS_CARD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hinges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LCD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LCD_Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Palm_Rest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PORTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SATA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop_id', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('battery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battery', to='catalog.battery')),
                ('bottom_cover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottom_cover', to='catalog.bottom_cover')),
                ('charger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charger', to='catalog.charger')),
                ('charging_port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charging_port', to='catalog.charging_port')),
                ('cpu_fan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_fan', to='catalog.cpu_fan')),
                ('graphics_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graphics_card', to='catalog.graphics_card')),
                ('hinges', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hinges', to='catalog.hinges')),
                ('keyboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyboard', to='catalog.keyboard')),
                ('lcd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lcd', to='catalog.lcd')),
                ('lcd_cover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lcd_cover', to='catalog.lcd_cover')),
                ('palm_rest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='palm_rest', to='catalog.palm_rest')),
                ('ports', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ports', to='catalog.ports')),
                ('ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ram', to='catalog.ram')),
                ('sata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sata', to='catalog.sata')),
            ],
        ),
    ]
