# Generated by Django 4.0.3 on 2022-03-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_laptop_battery_remove_laptop_bottom_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='laptop_id',
            field=models.ManyToManyField(null=True, to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='bottom_cover',
            name='laptop_id',
            field=models.ManyToManyField(null=True, to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='charger',
            name='laptop_id',
            field=models.ManyToManyField(null=True, to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='charging_port',
            name='laptop_id',
            field=models.ManyToManyField(null=True, to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='cpu_fan',
            name='laptop_id',
            field=models.ManyToManyField(null=True, to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='graphics_card',
            name='laptop_id',
            field=models.ManyToManyField(null=True, to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='hinges',
            name='laptop_id',
            field=models.ManyToManyField(null=True, to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='laptop_id',
            field=models.ManyToManyField(null=True, to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='lcd',
            name='laptop_id',
            field=models.ManyToManyField(null=True, to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='lcd_cover',
            name='laptop_id',
            field=models.ManyToManyField(null=True, to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='palm_rest',
            name='laptop_id',
            field=models.ManyToManyField(null=True, to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='ports',
            name='laptop_id',
            field=models.ManyToManyField(null=True, to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='laptop_id',
            field=models.ManyToManyField(null=True, to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='sata',
            name='laptop_id',
            field=models.ManyToManyField(null=True, to='catalog.laptop'),
        ),
    ]
