# Generated by Django 4.0.3 on 2022-03-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_battery_battery_id_bottom_cover_bottom_cover_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='laptop_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
