# Generated by Django 4.0.3 on 2022-03-27 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_alter_laptop_laptop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='country_id',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
        migrations.AddField(
            model_name='battery',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bottom_cover',
            name='country_id',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
        migrations.AddField(
            model_name='bottom_cover',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charger',
            name='country_id',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
        migrations.AddField(
            model_name='charger',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charging_port',
            name='country_id',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
        migrations.AddField(
            model_name='charging_port',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cpu_fan',
            name='country_id',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
        migrations.AddField(
            model_name='cpu_fan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='graphics_card',
            name='country_id',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
        migrations.AddField(
            model_name='graphics_card',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hinges',
            name='country_id',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
        migrations.AddField(
            model_name='hinges',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='country_id',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laptop',
            name='country_id',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
        migrations.AddField(
            model_name='laptop',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lcd',
            name='country_id',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
        migrations.AddField(
            model_name='lcd',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lcd_cover',
            name='country_id',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
        migrations.AddField(
            model_name='lcd_cover',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='palm_rest',
            name='country_id',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
        migrations.AddField(
            model_name='palm_rest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ports',
            name='country_id',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
        migrations.AddField(
            model_name='ports',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ram',
            name='country_id',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
        migrations.AddField(
            model_name='ram',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sata',
            name='country_id',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
        migrations.AddField(
            model_name='sata',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='battery',
            name='laptop_id',
            field=models.ManyToManyField(to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='bottom_cover',
            name='bottom_cover_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='bottom_cover',
            name='laptop_id',
            field=models.ManyToManyField(to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='charger',
            name='laptop_id',
            field=models.ManyToManyField(to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='charging_port',
            name='laptop_id',
            field=models.ManyToManyField(to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='cpu_fan',
            name='laptop_id',
            field=models.ManyToManyField(to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='graphics_card',
            name='laptop_id',
            field=models.ManyToManyField(to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='hinges',
            name='laptop_id',
            field=models.ManyToManyField(to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='laptop_id',
            field=models.ManyToManyField(to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='lcd',
            name='laptop_id',
            field=models.ManyToManyField(to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='lcd_cover',
            name='laptop_id',
            field=models.ManyToManyField(to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='palm_rest',
            name='laptop_id',
            field=models.ManyToManyField(to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='ports',
            name='laptop_id',
            field=models.ManyToManyField(to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='laptop_id',
            field=models.ManyToManyField(to='catalog.laptop'),
        ),
        migrations.AlterField(
            model_name='sata',
            name='laptop_id',
            field=models.ManyToManyField(to='catalog.laptop'),
        ),
    ]
