# Generated by Django 4.0.3 on 2022-03-29 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0008_rename_battery_id_battery_battery_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftHinge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_hinge_model', models.CharField(max_length=200, null=True, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('country_id', django_countries.fields.CountryField(max_length=2)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('laptop_model', models.ManyToManyField(to='catalog.laptop')),
            ],
        ),
        migrations.CreateModel(
            name='RightHinge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_hinge_model', models.CharField(max_length=200, null=True, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('country_id', django_countries.fields.CountryField(max_length=2)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('laptop_model', models.ManyToManyField(to='catalog.laptop')),
            ],
        ),
        migrations.DeleteModel(
            name='Hinges',
        ),
    ]
