# Generated by Django 4.0.3 on 2022-03-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_rename_righthinge_left_hinge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='bottom_cover',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='charger',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='charging_port',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='cpu_fan',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='graphics_card',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='lcd',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='lcd_cover',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='left_hinge',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='palm_rest',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='ports',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='right_hinge',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='sata',
            name='country_id',
        ),
    ]
