# Generated by Django 4.0.3 on 2022-03-31 01:48

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_battery_country_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battery',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='bottom_cover',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='charger',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='charging_port',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='cpu_fan',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='graphics_card',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='keyboard',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='laptop',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='lcd',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='lcd_cover',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='left_hinge',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='palm_rest',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='ports',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='right_hinge',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='sata',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='battery',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bottom_cover',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='charger',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='charging_port',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cpu_fan',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='graphics_card',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='laptop',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lcd',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lcd_cover',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='left_hinge',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='palm_rest',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ports',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ram',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='right_hinge',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sata',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='battery',
            name='battery_model',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bottom_cover',
            name='bottom_cover_model',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='charger',
            name='charger_model',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='charging_port',
            name='charging_port_model',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cpu_fan',
            name='cpu_fan_model',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='graphics_card',
            name='graphics_model',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='keyboard_model',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='country_id',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='lcd',
            name='lcd_model',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lcd_cover',
            name='lcd_cover_model',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='left_hinge',
            name='left_hinge_model',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='palm_rest',
            name='palm_rest_model',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ports',
            name='ports_model',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ram',
            name='ram_model',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='right_hinge',
            name='right_hinge_model',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sata',
            name='sata_model',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
