# Generated by Django 4.0.3 on 2022-04-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_serial_number_laptop_manufacturer_laptop_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='manufacturer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='series',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
