# Generated by Django 4.0.3 on 2022-04-06 00:45

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_laptop_manufacturer_alter_laptop_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='country_id',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
