# Generated by Django 4.0.3 on 2022-04-15 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_laptop_image_alter_part_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='part',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
