# Generated by Django 4.0.3 on 2022-04-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_laptop_image_alter_part_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='series',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
